### PR TITLE
Added deployment trigger for merges to master

### PR DESCRIPTION
**Pull request by M-Valentino**
It is a good idea to have this feature for complex repos or repos with multiple contributors.

### CODE REVIEW

**Comment by bcomnes** [comment]
When you merge a pull request, it triggers the push event on the target branch.

**Comment by M-Valentino** [comment]
Maybe something was happening on Neocities, but it appeared to not trigger for me when I merged.

**Comment by bcomnes** [comment]
You want it to deploy off the merge commit, not the head commit of the closed pr. This change would trigger on the pr commit on close. 

If your default branch is main, then switching the push commit to main should be fine. 

Can you share a pr that was merged that didn't trigger?

**Comment by bcomnes** [comment]
Cleaning up issues and closing this because this would lead to incorrect behavior.

**Pull request closed without merging**
